{% set name = "gcta" %}
{% set version = "1.93.2beta" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://cnsgenomics.com/software/{{ name }}/bin/{{ name }}_{{ version }}.zip
  sha256: 44354f4909666b760ab3cf538dc143ee3feff5540c2ad237a098766ff9829374

build:
  number: 0

requirements:
  host:
    - zlib
  run:
    - zlib
test:
  commands:
    - gcta | grep "Analysis started"

about:
  home: "https://cnsgenomics.com/software/gcta/"
  license: MIT
  summary: GCTA (Genome-wide Complex Trait Analysis) was initially designed to estimate the proportion of phenotypic variance explained by all genome-wide SNPs for complex traits (i.e., the GREML method). It has been subsequently extended for many other analyses to better understand the genetic architecture of complex traits.

extra:
  identifiers:
    - biotools:gcta
    - doi:10.1016/j.ajhg.2010.11.011 